#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - sudo apt-get install -y apt-transport-https software-properties-common wget
  - sudo mkdir -p /etc/apt/keyrings/
  - wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
  - echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
  - apt update
  - apt install -y grafana
  - systemctl daemon-reload
  - systemctl start grafana-server
  - systemctl status grafana-server
  - systemctl enable grafana-server.service

final_message: "The system is finally up, after $UPTIME seconds"
