#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - wget https://repo.zabbix.com/zabbix/7.0/ubuntu-arm64/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu22.04_all.deb
  - dpkg -i zabbix-release_7.0-2+ubuntu22.04_all.deb
  - apt update
  - apt install -y zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent
  - echo "create database zabbix character set utf8mb4 collate utf8mb4_bin;" | mysql -uroot -ppassword
  - echo "create user zabbix@localhost identified by 'zabbix';" | mysql -uroot -ppassword
  - echo "grant all privileges on zabbix.* to zabbix@localhost;" | mysql -uroot -ppassword
  - echo "set global log_bin_trust_function_creators = 1;" | mysql -uroot -ppassword
  - zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 --database=zabbix -uzabbix -pzabbix
  - echo "set global log_bin_trust_function_creators = 0;" | mysql -uroot -ppassword
  - systemctl restart zabbix-server zabbix-agent apache2
  - systemctl enable  zabbix-server zabbix-agent apache2

final_message: "The system is finally up, after $UPTIME seconds"
