#cloud-config
package_update: true
package_upgrade: true

runcmd:
  # Setup Repositories
  - wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu22.04_all.deb
  - DEBIAN_FRONTEND=noninteractive dpkg -i zabbix-release_7.0-2+ubuntu22.04_all.deb

  - wget https://dev.mysql.com/get/mysql-apt-config_0.8.32-1_all.deb
  - DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.32-1_all.deb

  - wget https://repos.influxdata.com/influxdata-archive.key
  - cat influxdata-archive.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/influxdata-archive.gpg > /dev/null
  - echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main' | tee /etc/apt/sources.list.d/influxdata.list

  # Install Softwares
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y influxdb2 mysql-server zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-sql-scripts zabbix-agent

  # Setup Database
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --database=mysql -uroot -ppassword
  - echo "create database zabbix character set utf8mb4 collate utf8mb4_bin;" | mysql -uroot -ppassword
  - echo "create user zabbix@localhost identified by 'zabbix';" | mysql -uroot -ppassword
  - echo "grant all privileges on zabbix.* to zabbix@localhost;" | mysql -uroot -ppassword

  - echo "create user grafana identified by 'grafana';" | mysql -uroot -ppassword
  - echo "grant select on zabbix.* to grafana;" | mysql -uroot -ppassword

  - echo "set global log_bin_trust_function_creators = 1;" | mysql -uroot -ppassword
  - zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 --database=zabbix -uzabbix -pzabbix
  - echo "set global log_bin_trust_function_creators = 0;" | mysql -uroot -ppassword

  # Setup Zabbix
  - echo 'DBPassword=zabbix' >> /etc/zabbix/zabbix_server.conf

  # Start services
  - systemctl restart zabbix-server zabbix-agent apache2 influxdb
  - systemctl enable  zabbix-server zabbix-agent apache2 influxdb

final_message: "The system is finally up, after $UPTIME seconds"
